steps:
- name: 'docker/compose:1.19.0'
  args: ['build']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'omdb-app-backend_movies-service:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']